### ISSUE TITLE
Problems with asset-loader using dist or stage with play 2.2.1

### ISSUE THREAD

**Issue by larousso** [edeustace/assets-loader#10]
Hi, 

I have problem with the production mode. I have some errors when my project is packaged using play dist or after play stage. 

The error is the followings : 

play.api.Application$$anon$1: Execution exception[[FileNotFoundException: /Users/adelegue/Documents/test/covoiturage-test/target/universal/covoiturage-java-1.0-SNAPSHOT/target/scala-2.10/classes/public/main--591140239.min.js (No such file or directory)]]
    at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
Caused by: java.io.FileNotFoundException: /Users/adelegue/Documents/test/covoiturage-test/target/universal/covoiturage-java-1.0-SNAPSHOT/target/scala-2.10/classes/public/main--591140239.min.js (No such file or directory)
    at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_45]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_45]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:110) ~[na:1.7.0_45]
    at java.io.FileWriter.<init>(FileWriter.java:63) ~[na:1.7.0_45]
    at com.ee.utils.file.package$.writeToFile(package.scala:10) ~[com.ee.assets-loader_2.10-0.11.1.jar:0.11.1]
    at com.ee.assets.Loader.minifyJs(Loader.scala:77) ~[com.ee.assets-loader_2.10-0.11.1.jar:0.11.1]

It's a bit obscure for me :) 

Thanks,
Alex

**Comment by edeustace** [comment]
This was fixed in an earlier version: https://github.com/edeustace/assets-loader/pull/6. Will need to check that fix has been brought forward to the latest version.

**Comment by larousso** [comment]
I think I 've found one problem. I had this problems on heroku 

on heroku, the folder scala-\* is dropped :
https://devcenter.heroku.com/articles/play-support

This exception is thrown : 
java.lang.RuntimeException: can't find scala-${version} folder 

I think that the solution is to configure a jarfile name on the conf.
But I have found this : 
private def initAssetsFolder: File = {
    classesFolder orElse explodedJarFolder getOrElse {
      throw new AssetsLoaderException("Error can't find a class folder or exploded jar folder")
    }
  }

where classesFolder throw the exception so explodedJarFolder is never executed

Generaly, I think the target/scala-{version} folder is not used using stage mode. 

May be you can test if target/universal/stage/bin/<app-name> folder exist.

**Comment by edeustace** [comment]
Hi - I've only just realised that stage mode in 2.2.1 now generates the binaries in a completely different folder structure - so that part of the will need to be updated to make use of that. May not be until after the 25th.

**Comment by edeustace** [comment]
@larousso have a look at the latest snapshot - see if that's working for you.

**Comment by larousso** [comment]
I already have an error, here is the stacktrace :

play.api.Application$$anon$1: Execution exception[[AssetsLoaderException: concatFiles: snap.min.jsangular.jsui-bootstrap-tpls.min.jscontroller.jsapp.js]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
Caused by: com.ee.assets.exceptions.AssetsLoaderException: concatFiles: snap.min.jsangular.jsui-bootstrap-tpls.min.jscontroller.jsapp.js
        at com.ee.assets.processors.SimpleFileProcessor$$anonfun$6.apply(SimpleFileProcessor.scala:187) ~[com.ee.assets-loader_2.10-0.11.2-SNAPSHOT.jar:0.11.2-SNAPSHOT]
        at com.ee.assets.processors.SimpleFileProcessor$$anonfun$6.apply(SimpleFileProcessor.scala:181) ~[com.ee.assets-loader_2.10-0.11.2-SNAPSHOT.jar:0.11.2-SNAPSHOT]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.collection.immutable.List.foreach(List.scala:318) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:277) ~[na:1.7.0_45]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338) ~[na:1.7.0_45]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[na:1.7.0_45]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.7.0_45]
        at java.io.BufferedReader.fill(BufferedReader.java:154) ~[na:1.7.0_45]
        at java.io.BufferedReader.read(BufferedReader.java:175) ~[na:1.7.0_45]

I have not search why. 
Enjoy your christmas day, 
Alex

**Comment by edeustace** [comment]
Can you send/link to a sample project that throws this error? Also can you try running the example app to see if that is working for you?

**Comment by larousso** [comment]
I m working on this app : https://github.com/larousso/covoiturage

I didn't try with the sample. I reproduce the error doing : 
play clean stage 
and then 
target/universal/stage/bin/<appname>

If you try my app, you need a mongodb database and you can run : 
play clean stage 
target/universal/stage/bin/covoiturage-java -Dconfig.resource=dev.conf

**Comment by edeustace** [comment]
k - will have a look - cheers for the feedback.

**Comment by edeustace** [comment]
@larousso - I see it was failing to read the angular.js file in your app, due to a MalformedInputException. I've fixed that and pushed a new snapshot.

**Comment by larousso** [comment]
It works and on heroku too !
Thanks to be so speed to fix it :)

**Comment by twiho** [comment]
Hey guys, I seem to have a similar problem:

2014-01-20 16:21:30,193 - [ERROR] - from akka.actor.ActorSystemImpl in play-akka.actor.default-dispatcher-2
Uncaught error from thread [play-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.ExceptionInInitializerError: null
    at views.html.layouts.main$.apply(main.template.scala:104) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at views.html.Application.index$.apply(index.template.scala:48) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at views.html.Application.index$.render(index.template.scala:198) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at views.html.Application.index.render(index.template.scala) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at controllers.Application.renderIndex(Application.java:130) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at controllers.Application.indexCached(Application.java:113) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at controllers.Application.index(Application.java:94) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$332$$anonfun$apply$332.apply(routes_routing.scala:4018) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$332$$anonfun$apply$332.apply(routes_routing.scala:4018) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:na]
    at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at Global$1.call(Global.java:158) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:na]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:20) ~[com.typesafe.play.play-java-jpa_2.10-2.2.1.jar:2.2.1]
    at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:18) ~[com.typesafe.play.play-java-jpa_2.10-2.2.1.jar:2.2.1]
    at play.db.jpa.JPA.withTransactionAsync(JPA.java:177) ~[com.typesafe.play.play-java-jpa_2.10-2.2.1.jar:2.2.1]
    at play.db.jpa.TransactionalAction.call(TransactionalAction.java:15) ~[com.typesafe.play.play-java-jpa_2.10-2.2.1.jar:2.2.1]
    at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: com.ee.assets.exceptions.AssetsLoaderException: Error can't find a class folder or exploded jar folder
    at com.ee.utils.play.package$$anonfun$initAssetsFolder$3.apply(package.scala:31) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at com.ee.utils.play.package$$anonfun$initAssetsFolder$3.apply(package.scala:31) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at scala.Option.getOrElse(Option.scala:120) ~[org.scala-lang.scala-library-2.10.2.jar:na]
    at com.ee.utils.play.package$.initAssetsFolder(package.scala:31) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at com.ee.utils.play.package$.assetsFolder(package.scala:17) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at com.ee.assets.Loader.assetsFolder$lzycompute(Loader.scala:103) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at com.ee.assets.Loader.assetsFolder(Loader.scala:103) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at com.ee.assets.Loader.<init>(Loader.scala:40) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    at views.Helper$.<init>(Helper.scala:8) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    at views.Helper$.<clinit>(Helper.scala) ~[prizeo.prizeo-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
    ... 31 common frames omitted
Caused by: java.lang.Throwable: null
    at com.ee.assets.exceptions.AssetsLoaderException.<init>(AssetsLoaderException.scala:4) ~[com.ee.assets-loader_2.10-0.11.3.jar:0.11.3]
    ... 41 common frames omitted

Anybody any idea on what the issue may be? We're running:
val assetsLoader = "com.ee" %% "assets-loader" % "0.11.3"
  val assetsLoaderReleases = "ed eustace" at "http://edeustace.com/repository/releases"

as the previous version caused other problems. The config:

  prod : {
    concatenate: true
    minify: true
    gzip: true
    # Optional: specify a jar from which to extract the 'public' assets folder.
    # by default it'll use the main play app jar in the dist folder
    # jarfile: "prizeo.prizeo-2.0-SNAPSHOT.jar"
  }

**Comment by edeustace** [comment]
Can you provide a sample project that has the error?

**Comment by jkypet** [comment]
Hi, I have created that sample project here: https://github.com/jkypet/assets-loader-test

It's generic play 2.2.1 application with these changes: 
- added dependency for assets-loader (project/Build.scala)
- changed default route for assets in routes file
- created Helper for templates (views/Helper.scala)
- added assetsLoader.conf
- added css and javascript loader in main.scala.html
- added new css and javascript file for testing purposes 

When I call RUN everything works, but with START and DIST I get the exception from previous comment.

**Comment by edeustace** [comment]
@jkypet I'm going to move this to a new issue: #13 .

**Comment by phedoreanu** [comment]
Hey @edeustace,

I get the same error as @larousso when deploying the Play app in a Docker container:
```
play.api.Application$$anon$1: Execution exception[[MalformedInputException: Input length = 1]]
	at play.api.Application$class.handleError(Application.scala:289) ~[play.play_2.10-2.1.3.jar:2.1.3]
	at play.api.DefaultApplication.handleError(Application.scala:383) [play.play_2.10-2.1.3.jar:2.1.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$18$$anonfun$apply$18.apply(PlayDefaultUpstreamHandler.scala:314) [play.play_2.10-2.1.3.jar:2.1.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$18$$anonfun$apply$18.apply(PlayDefaultUpstreamHandler.scala:312) [play.play_2.10-2.1.3.jar:2.1.3]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play.play_2.10-2.1.3.jar:2.1.3]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play.play_2.10-2.1.3.jar:2.1.3]
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:277) ~[na:1.7.0_65]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338) ~[na:1.7.0_65]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[na:1.7.0_65]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.7.0_65]
	at java.io.BufferedReader.fill(BufferedReader.java:154) ~[na:1.7.0_65]
	at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[na:1.7.0_65]
```

Works fine if deployed on a normal Linux machine. Do I just need to upgrade to the latest Play version?
Or am I missing some package to install?

Thank you,
Adrian
