### ISSUE TITLE
Play 2.1.x and production

### ISSUE THREAD

**Issue by rvangsgaard** [edeustace/assets-loader#5]
Have you been running this in production? When I deploy in production, the "target" folder is not available. You use it here: 
https://github.com/edeustace/assets-loader/blob/211_version/plugin/app/com/ee/utils/play/package.scala - line 11

```
Caused by: java.lang.NullPointerException: null
    at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:111) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:111) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.SeqLike$class.size(SeqLike.scala:102) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:105) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.ListBuffer.sizeHint(ListBuffer.scala:45) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.TraversableLike$class.to(TraversableLike.scala:628) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.ArrayOps$ofRef.to(ArrayOps.scala:105) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:243) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at scala.collection.mutable.ArrayOps$ofRef.toList(ArrayOps.scala:105) ~[org.scala-lang.scala-library-2.10.0.jar:na]
    at com.ee.utils.play.package$.classesFolder(package.scala:11) ~[com.ee.assets-loader_2.10-0.10.1-8ab100a.jar:0.10.1-8ab100a]
    at com.ee.assets.Loader.targetFolder$lzycompute(Loader.scala:96) ~[com.ee.assets-loader_2.10-0.10.1-8ab100a.jar:0.10.1-8ab100a]
    at com.ee.assets.Loader.targetFolder(Loader.scala:94) ~[com.ee.assets-loader_2.10-0.10.1-8ab100a.jar:0.10.1-8ab100a]
    at com.ee.assets.Loader.<init>(Loader.scala:33) ~[com.ee.assets-loader_2.10-0.10.1-8ab100a.jar:0.10.1-8ab100a]
```

**Comment by edeustace** [comment]
Hi, yes this is an issue.
Will investigate what needs to change to work with production mode.

**Comment by edeustace** [comment]
The asset loader will now extract the 'public' folder from the application jar when in dist mode.
